language: php
php:
    - "7.3"

jobs:
    include:
        - stage: test
          script:
            - echo 'Build starts'
            - echo 'Installing dependencies...'
            - composer install --no-ansi --no-progress --quiet
            - echo 'Checking build'
            - bin/console cache:clear
            - vendor/bin/phpstan analyse --level 7 --memory-limit=512M --no-progress
            - vendor/bin/php-cs-fixer fix --config=.php_cs.dist -v --dry-run --stop-on-violation --allow-risky yes --using-cache=no
            - bin/phpunit --coverage-text

        - stage: deploy
          script:
              - echo "$DEPLOY_SERVER_PUBLIC_KEY" >> $HOME/.ssh/known_hosts
              - ssh -p "$DEPLOY_SERVER_PORT" "$DEPLOY_SERVER_USER@$DEPLOY_SERVER_ADDRESS"

stages:
    - name: test
    - name: deploy
      if: branch = master